// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Diquview: typeof import('./src/components/diquview/index.vue')['default']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Errarea: typeof import('./src/components/errarea/index.vue')['default']
    Mapview: typeof import('./src/components/mapview/index.vue')['default']
    Screenview: typeof import('./src/components/screenview/index.vue')['default']
    Time: typeof import('./src/components/time/index.vue')['default']
  }
}
